defaults:
  - env_vars: env_vars
  - _self_

seed: 42
window_size: 30
goal_window_size: 0
eval_window_size: 0
batch_size: 1024
epochs: 1000
eval_freq: 10
eval_on_env_freq: 0
num_env_evals: 0
num_final_evals: 0
num_final_eval_per_goal: 0
action_window_size: 5

wandb:
  project: "vq-bet"
  entity: ${env_vars.wandb_entity}

device: cpu
optim:
  lr: 5.5e-5
  weight_decay: 2e-4
  betas: [0.9, 0.999]


data:
  _target_: TODO
  TODO

save_every: 10
save_path: "${env_vars.save_path}/checkpoints/${env.gym.id}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
load_path: null

vqvae_model:
  _target_: vqvae.VqVae
  obs_dim: TODO
  input_dim_h: ${action_window_size}
  input_dim_w: 8
  n_latent_dims: 512
  vqvae_n_embed: 16
  vqvae_groups: 2
  eval: false
  device: ${device}
  encoder_loss_multiplier: 1
  