save_path: "/home/franka/Desktop/capstone_stack/VQ-BeT/saved"

device: "cpu"

train:
  batch_size: 32
  epochs: 1000
  save_interval: 1

split_dataset:
  _target_: "dataset.split_dataset"
  train_split: 0.95

vqvae:
  _target_: "vqvae.vqvae.VqVae"
  obs_dim: 1024  # Unused
  input_dim_h: 5  # Sequence length of action chunk
  input_dim_w: 8  # Action dimension
  n_latent_dims: 512
  vqvae_n_embed: 32
  vqvae_groups: 4
  eval: true
  device: "cpu"
  load_dir: null
  encoder_loss_multiplier: 1.0
  act_scale: 1.0

dataset:
  _target_: "dataset.FrankaDataset"
  data_folder: "/home/franka/Desktop/capstone_stack/Data/sample_data"
  sequence_length: 5
  step_size: 2
  frequency: 5

wandb:
  project: "VQ-BeT"
  run_name: "vqvae_training_run"