_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
dataset:
    value:
        _target_: dataset.FrankaDataset
        data_folder: /home/franka/Desktop/capstone_stack/Data/sample_data
        frequency: 5
        sequence_length: 5
        step_size: 2
device:
    value: cpu
save_path:
    value: /home/franka/Desktop/capstone_stack/VQ-BeT/saved
split_dataset:
    value:
        _target_: dataset.split_dataset
        train_split: 0.95
train:
    value:
        batch_size: 32
        epochs: 1000
        save_interval: 1
vqvae:
    value:
        _target_: vqvae.vqvae.VqVae
        act_scale: 1
        device: cpu
        encoder_loss_multiplier: 1
        eval: true
        input_dim_h: 5
        input_dim_w: 8
        load_dir: null
        n_latent_dims: 512
        obs_dim: 1024
        vqvae_groups: 4
        vqvae_n_embed: 32
wandb:
    value:
        project: VQ-BeT
        run_name: vqvae_training_run
